version: '3.9'

services: 
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=epdev
      - MONGO_INITDB_ROOT_PASSWORD=EPmongodb47
    volumes:
      - ./mongo_data:/data/db